baseURL = 'https://vf2e.github.io/blog/'
languageCode = 'zh-cn'
title = '我的技术博客'
theme = 'PaperMod'

[params]
defaultTheme = "auto"
author = "Me"

[[params.socialIcons]]
name = "github"
url = "https://github.com/vf2e"
